name: MSYS2
on: [push, pull_request]

jobs:
  msys2-ucrt64-build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git mingw-w64-ucrt-x86_64-cmake mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-openblas mingw-w64-ucrt-x86_64-opencv mingw-w64-ucrt-x86_64-python-pip mingw-w64-ucrt-x86_64-python-matplotlib mingw-w64-ucrt-x86_64-python-wheel mingw-w64-ucrt-x86_64-tk
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          ./.github/workflows/ci-build.sh
      # - name: Produce downloadable executable
      #   uses: actions/upload-artifacts@v3
      #   with:
          
